GET http://localhost:8081/flowers/

###
POST http://localhost:8081/flowers/
Content-Type: application/json


{
  "sepalLength": 100,
  "flowerColor": "RED",
  "flowerType": "ROSE",
  "price": 100
}

# {
#   "sepalLength": 10,
#   "flowerColor": "YELLOW",
#   "flowerType": "CHAMOMILE",
#   "price": 10
# }
